---
title: "Getting Start with Git and GitHub for R Users"
author: "Saghir Bashir"
date: "`r format(Sys.time(), '%a %d %b %Y (%H:%M:%S)')`"
output:
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js
    css: [tweaks.css, default, robot-fonts]
    self_contained: true
    # lib_dir: libs
    # https://github.com/gnab/remark/wiki/Configuration
    nature:
      ratio: 16:9
      highlightStyle: default
      highlightLanguage: r
      highlightLines: true
      highlightSpans: false
      countIncrementalSlides: false
      slideNumberFormat: "%current%"
    seal: false
---

```{r setup, include=FALSE}
library(here)
library(knitr)
library(kableExtra)

# Copied & modified from: https://github.com/gadenbuie/gentle-ggplot2 (Index.Rmd)
#
# Thanks to Garrick Aden-Buie (https://www.garrickadenbuie.com/) for sharing :)
#

knitr::opts_chunk$set(fig.width=4.4, fig.height=3.2, fig.retina=4,
                      out.width = "100%",
                      message=FALSE, warning=FALSE, cache = TRUE, 
                      autodep = TRUE, hiline=TRUE)

knitr::opts_hooks$set(fig.callout = function(options) {
  if (options$fig.callout) {
    options$echo <- FALSE
    options$out.height <- "99%"
    options$fig.width <- 16
    options$fig.height <- 8
  }
  options
})

options(
  htmltools.dir.version = FALSE, 
  width = 90,
  # max.print = 9999,
  knitr.table.format = "html"
)

```

class: middle, center

<div class="git-icon-left-top"></div> 
<div class="GH-Octocat-right-bottom"></div> 
<div class="rlogo-logo-left-bottom"></div> 

# Getting Start with Git

# and GitHub for R Users

<br>

### Saghir Bashir<br><br>24th May 2019


---
class: inverse, middle, center

# Relax

# Experiment

# Make Mistakes

# Learn

# Enjoy

---
class: middle, center

<div class="git-icon-left-top"></div> 
<div class="GH-Octocat-right-bottom"></div> 
<div class="rlogo-logo-left-bottom"></div> 

# Outline

## Motivation

## Discover GitHub

## Git to GitHub

## Summary

---
class: inverse, middle, center

# Motivation
<br>
# Why?

---
<div class="rlogo-logo-right-top"></div>

# Developing an R Program

.pull-left[
## R Program
```
# Thesis Project Data Cleaning
library(data.table)
library(here)

tdata <- fread(here("mydata.csv"))

... some data cleaning code here ...

```
]

--

.pull-right[
## Processing R Program

1. Save as "thesis-data.R"

]

---
<div class="rlogo-logo-right-top"></div>

# Developing an R Program

.pull-left[
## R Program
```
# Thesis Project Data Cleaning
library(data.table)
library(here)

tdata <- fread(here("mydata.csv"))

... some data cleaning code here ...

... some more data cleaning code here ...


```
]

.pull-right[
## Processing R Program

1. Save as "thesis-data.R" 
2. Overwrite "thesis-data.R" 
]

---
<div class="rlogo-logo-right-top"></div>

# Developing an R Program

.pull-left[
## R Program
```
# Thesis Project Data Cleaning
library(data.table)
library(here)

tdata <- fread(here("mydata.csv"))

... some data cleaning code here ...

... some more data cleaning code here ...

... summary statistics to check data ...


```
]

.pull-right[
## Processing R Program

1. Save as "thesis-data.R" 
2. Overwrite "thesis-data.R" 
3. Overwrite "thesis-data.R" again
]

---
<div class="rlogo-logo-right-top"></div>

# Developing an R Program

.pull-left[
## R Program
```
# Thesis Project Data Cleaning
library(data.table)
library(here)

tdata <- fread(here("mydata.csv"))

... some data cleaning code here ...

... MODIFY data cleaning code here ...

... summary statistics to check data ...


```
]

.pull-right[
## Processing R Program

1. Save as "thesis-data.R" 
2. Overwrite "thesis-data.R" 
3. Overwrite "thesis-data.R" again
4. Overwrite "thesis-data.R" with modification
]

---
<div class="rlogo-logo-right-top"></div>
<div class="emoji-crying-right-bottom"></div>

# Developing an R Program

.pull-left[
## R Program
```
# Thesis Project Data Cleaning
library(data.table)
library(here)

tdata <- fread(here("mydata.csv"))

... some data cleaning code here ...

... MODIFY data cleaning code here ...

... summary statistics to check data ...

!!! Modified code messed up summary statitics !!!

!! Previous code worked better  !!!

```
]

.pull-right[
## Processing R Program

1. Save as "thesis-data.R" 
2. Overwrite "thesis-data.R" 
3. Overwrite "thesis-data.R" again
4. Overwrite "thesis-data.R" with modification
5. Redo work that you did before
]




---
<div class="rlogo-logo-right-top"></div>

# R Program -- Saving Versions

.pull-left[
## R Program
```
# Thesis Project Data Cleaning
library(data.table)
library(here)

tdata <- fread(here("mydata.csv"))

... some data cleaning code here ...

```
]

--

.pull-right[
## Processing R Program

1. Save as "thesis-data-01.R"

]

---
<div class="rlogo-logo-right-top"></div>

# R Program -- Saving Versions

.pull-left[
## R Program
```
# Thesis Project Data Cleaning
library(data.table)
library(here)

tdata <- fread(here("mydata.csv"))

... some data cleaning code here ...

... some more data cleaning code here ...


```
]

.pull-right[
## Processing R Program

1. Save as "thesis-data-01.R" 
2. Save as "thesis-data-02.R" 
]

---
<div class="rlogo-logo-right-top"></div>

# R Program -- Saving Versions

.pull-left[
## R Program
```
# Thesis Project Data Cleaning
library(data.table)
library(here)

tdata <- fread(here("mydata.csv"))

... some data cleaning code here ...

... some more data cleaning code here ...

... summary statistics to check data ...


```
]

.pull-right[
## Processing R Program

1. Save as "thesis-data-01.R" 
2. Save as "thesis-data-02.R" 
3. Save as "thesis-data-03.R" 
]

---
<div class="rlogo-logo-right-top"></div>

# R Program -- Saving Versions

.pull-left[
## R Program
```
# Thesis Project Data Cleaning
library(data.table)
library(here)

tdata <- fread(here("mydata.csv"))

... some data cleaning code here ...

... MODIFY data cleaning code here ...

... summary statistics to check data ...


```
]

.pull-right[
## Processing R Program
1. Save as "thesis-data-01.R" 
2. Save as "thesis-data-02.R" 
3. Save as "thesis-data-03.R" 
4. Save as "thesis-data-04.R" 
]

---
<div class="rlogo-logo-right-top"></div>

# R Program -- Saving Versions

.pull-left[
## R Program
```
# Thesis Project Data Cleaning
library(data.table)
library(here)

tdata <- fread(here("mydata.csv"))

... some data cleaning code here ...

... MODIFY data cleaning code here ...

... summary statistics to check data ...

!!! Modified code messed up summary statitics !!!

... If I remember I can go back version 03 !!!

... Fixed send this final version to supervisor, ... 

```
]

.pull-right[
## Processing R Program

1. Save as "thesis-data-01.R" 
2. Save as "thesis-data-02.R" 
3. Save as "thesis-data-03.R" 
4. Save as "thesis-data-04.R" 
5. Save as "thesis-data-Final.R" 
]

---
<div class="rlogo-logo-right-top"></div>

# R Program -- Saving Versions

.pull-left[
## R Program
```
# Thesis Project Data Cleaning
library(data.table)
library(here)

tdata <- fread(here("mydata.csv"))

... some data cleaning code here ...

... MODIFY data cleaning code here ...

... summary statistics to check data ...

!!! Modified code messed up summary statitics !!!

... If I remember I can go back version 03 !!!

... Fixed send this final version to supervisor, ... 

```
]

.pull-right[
## Processing R Program

1. Save as "thesis-data-01.R" 
2. Save as "thesis-data-02.R" 
3. Save as "thesis-data-03.R" 
4. Save as "thesis-data-04.R" 
5. Save as "thesis-data-Final.R" 
6. Received "thesis-data-Final-Sup.R" from Supervisor
7. ... "thesis-data-Final-Sup-ME.R"
8. ... "thesis-data-Final-Sup-ME-minor.R"
9. ... "thesis-data-Final-Last.R"
...
]

---
class: inverse, middle, center

# Six months later...

---
<div class="rlogo-logo-right-top"></div>
<div class="emoji-thinking-right-bottom"></div>

## The future you...

.pull-left[
<br>

### Needs to update the project.

### Receives updated data.

### Discovers an error.

### Continues on the project.

### ...
]

.pull-right[
## Continue from where?

+ "thesis-data-01.R"                
+ "thesis-data-02.R"                
+ "thesis-data-03.R"                
+ "thesis-data-04.R"                
+ "thesis-data-Final-Last.R"        
+ "thesis-data-Final-Sup-ME-minor.R"
+ "thesis-data-Final-Sup-ME.R"      
+ "thesis-data-Final-Sup.R"         
+ "thesis-data-Final.R"      
...
]

---
<div class="emoji-exploding-head-right-bottom"></div>

# Other Issues

## What changed between files?

## What needs to be done?

## What issues are there?

## How can multiple people collaborate?

...

---
class: inverse, middle, center

<div class="git-icon-white-left-top"></div> 
<div class="GH-Mark-White-right-bottom"></div> 

# Git & GitHub

## Track changes

## Share your work 

## Collaborate 

## Track issues 


